---
- name: Add MongoDB key
  become: yes
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.4.asc
    state: present

- name: Add MongoDB repository
  become: yes
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse
    state: present

- name: Install mongodb
  become: yes
  apt:
    update_cache: yes
    name: mongodb-org
    state: present

- name: Create systemd service file
  become: yes
  template:
    src: mongod.service
    dest: /lib/systemd/system/mongod.service

- name: Enable Mongod service
  become: yes
  command: "{{ item }}"
  with_items:
    - systemctl --system daemon-reload
    - systemctl enable mongod.service

- name: Copy MongoDB configuration file
  become: yes
  template:
    src: mongod.conf
    dest: /etc/mongod.conf

- name: Restart mongodb
  become: yes
  service:
    name: mongod
    state: restarted
